# CONSTANTS

GRAVITY = 9.8 * np.array([0, 1, 0]) # m/s^2


# BEAM SOURCE PARAMETERS

SOURCE_ROTATIONAL_TEMPERATURE     = 4 # K
SOURCE_EXTRACTION_TIME_PROFILE    = 'normal'
SOURCE_EXTRACTION_TIME_PARAMETERS = (0, .0002) # (MEAN, STD) IN (s)
SOURCE_VELOCITY_DISTRIBUTION      = 'normal'
SOURCE_VELOCITY_PARAMETERS        = ((180, 0, 0), (13, 13, 13)) # (MEAN, STD) IN (m/s)
SOURCE_POSITION_DISTRIBUTION      = 'uniform circle'
SOURCE_POSITION_PARAMETERS        = (.0025, 0, 0, 0) # (RADIUS, X-POSITION, Y-OFFSET, Z-OFFSET) IN (m)

# COLLIMATING PARAMETERS

CONICAL_APERTURE_POSITION     = .025
CONICAL_APERTURE_RADIUS       = .003
CONICAL_APERTURE              = EllipticalCollimator(x=CONICAL_APERTURE_POSITION, y=0, z=0,
                                                     r=CONICAL_APERTURE_RADIUS)

FIXED_COLLIMATOR_POSITION     = 1.125
FIXED_COLLIMATOR_LENGTH       = .025
FIXED_COLLIMATOR              = RectangleCollimator(x=FIXED_COLLIMATOR_POSITION, y=0, z=0,
                                                    d=FIXED_COLLIMATOR_LENGTH)

# SPECIAL DESIGNATED LOCATIONS


STIRAP_POSITION         = 1.20
REFINEMENT_POSITION     = 1.23
READOUT_POSITION        = 1.45
GUARD_RING_EXIT_POSTION = 1.62